### ISSUE TITLE
Migrating TCK Plugin and RA for JBoss 7.2 and WildFly.

### ISSUE THREAD

**Issue by SergeyLee** [RestComm/jain-slee.more#1]
I was changed TCK Plugin and RA for JBoss 7.2 (https://github.com/RestComm/jain-slee.more/commit/a6702de0b664a16fbb7b795b4743dcf77ceb04df).

Then I started JBoss 7.2 with SecurityManager:

> export JAVA_OPTS="-Djava.security.manager -Djboss.home.dir=$JBOSS_HOME -Djava.security.policy==$TCK_HOME/tck-security-7.policy -Djava.security.debug=failure"
> $JBOSS_HOME/bin/standalone.sh

Policy file:
[tck-security-7.policy.txt](https://github.com/RestComm/jain-slee.more/files/634421/tck-security-7.policy.txt)
I added all codeBase which I needed for JBoss 7.2 + JSLEE 3.0.
Policy file for JBoss 5.1 + JSLEE 2.x: https://github.com/RestComm/jain-slee.more/blob/master/tck/jain-slee-1.1/tck-security.policy

Then I deployed TCK Plugin and get these errors:

18:33:30,823 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) JBAS015876: Starting deployment of "restcomm-slee-tck-plugin-bean.jar" (runtime-name: "restcomm-slee-tck-plugin-bean.jar")
18:33:31,250 INFO  [org.telestax.slee.container.build.as7.deployment.SleeDeploymentMetaData] (MSC service thread 1-4) METADATA deploymentRoot: ResourceRoot [root="/content/restcomm-slee-tck-plugin-bean.jar"]
18:33:31,250 INFO  [org.telestax.slee.container.build.as7.deployment.SleeDeploymentMetaData] (MSC service thread 1-4) METADATA rootFile: "/content/restcomm-slee-tck-plugin-bean.jar"
18:33:31,251 INFO  [org.telestax.slee.container.build.as7.deployment.SleeDeploymentMetaData] (MSC service thread 1-4) Cannot open stream (META-INF): /content/restcomm-slee-tck-plugin-bean.jar/META-INF/deployable-unit.xml
18:33:31,256 DEBUG [org.jboss.modules] (MSC service thread 1-3) Module ibm.jdk:main defined by local module loader @682d490b (finder: local module finder @7516a69b (roots: /opt/mobicents/restcomm-slee-3.0.Alpha/jboss-as-7.2.0.Final/modules,/opt/mobicents/restcomm-slee-3.0.Alpha/jboss-as-7.2.0.Final/modules/system/layers/base))
18:33:31,313 DEBUG [org.jboss.modules] (MSC service thread 1-4) Module deployment.restcomm-slee-tck-plugin-bean.jar:main defined by Service Module Loader
18:33:31,339 INFO  [org.jboss.as.ejb3.deployment.processors.EjbJndiBindingsDeploymentUnitProcessor] (MSC service thread 1-5) JNDI bindings for session bean named SleeTCKPluginWrapper in deployment unit deployment "restcomm-slee-tck-plugin-bean.jar" are as follows:

	java:global/restcomm-slee-tck-plugin-bean/SleeTCKPluginWrapper!org.mobicents.slee.test.suite.tckwrapper.SleeTCKPluginWrapperMBean
	java:app/restcomm-slee-tck-plugin-bean/SleeTCKPluginWrapper!org.mobicents.slee.test.suite.tckwrapper.SleeTCKPluginWrapperMBean
	java:module/SleeTCKPluginWrapper!org.mobicents.slee.test.suite.tckwrapper.SleeTCKPluginWrapperMBean
	java:global/restcomm-slee-tck-plugin-bean/SleeTCKPluginWrapper
	java:app/restcomm-slee-tck-plugin-bean/SleeTCKPluginWrapper
	java:module/SleeTCKPluginWrapper

18:33:31,420 INFO  [org.telestax.slee.container.build.as7.deployment.SleeDeploymentInstallProcessor] (MSC service thread 1-2) Deploy: deployment "restcomm-slee-tck-plugin-bean.jar"
18:33:31,421 TRACE [org.mobicents.slee.container.deployment.jboss.SLEESubDeployer] (MSC service thread 1-2) Method accepts called for file:/opt/mobicents/restcomm-slee-3.0.Alpha/jboss-as-7.2.0.Final/standalone/tmp/vfs/tempa5418daf0d8e6b8/restcomm-slee-tck-plugin-bean.jar-3a0a55604da26f85/restcomm-slee-tck-plugin-bean.jar/ [DU: restcomm-slee-tck-plugin-bean.jar]
18:33:31,421 TRACE [org.mobicents.slee.container.deployment.jboss.SLEESubDeployer] (MSC service thread 1-2) Method init called for jar:file:/opt/mobicents/restcomm-slee-3.0.Alpha/jboss-as-7.2.0.Final/standalone/tmp/vfs/tempa5418daf0d8e6b8/restcomm-slee-tck-plugin-bean.jar-3a0a55604da26f85/restcomm-slee-tck-plugin-bean.jar!/ [DU: restcomm-slee-tck-plugin-bean.jar]
18:33:31,421 TRACE [org.mobicents.slee.container.deployment.jboss.SLEESubDeployer] (MSC service thread 1-2) Method start called for file:/opt/mobicents/restcomm-slee-3.0.Alpha/jboss-as-7.2.0.Final/standalone/tmp/vfs/tempa5418daf0d8e6b8/restcomm-slee-tck-plugin-bean.jar-3a0a55604da26f85/restcomm-slee-tck-plugin-bean.jar/ [DU: restcomm-slee-tck-plugin-bean.jar]
18:33:31,469 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 26) MSC00001: Failed to start service jboss.deployment.unit."restcomm-slee-tck-plugin-bean.jar".component.SleeTCKPluginWrapper.START: org.jboss.msc.service.StartException in service jboss.deployment.unit."restcomm-slee-tck-plugin-bean.jar".component.SleeTCKPluginWrapper.START: java.lang.IllegalStateException: JBAS011048: Failed to construct component instance
	at org.jboss.as.ee.component.ComponentStartService$1.run(ComponentStartService.java:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [rt.jar:1.7.0_95]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [rt.jar:1.7.0_95]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_95]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_95]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_95]
	at org.jboss.threads.JBossThread.run(JBossThread.java:122) [jboss-threads-2.1.0.Final.jar:2.1.0.Final]
Caused by: java.lang.IllegalStateException: JBAS011048: Failed to construct component instance
	at org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:163)
	at org.jboss.as.ee.component.BasicComponent.createInstance(BasicComponent.java:85)
	at org.jboss.as.ejb3.component.singleton.SingletonComponent.getComponentInstance(SingletonComponent.java:126)
	at org.jboss.as.ejb3.component.singleton.SingletonComponent.start(SingletonComponent.java:141)
	at org.jboss.as.ee.component.ComponentStartService$1.run(ComponentStartService.java:54)
	... 6 more
Caused by: javax.ejb.EJBException: JBAS014580: Unexpected Error
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.handleExceptionInOurTx(CMTTxInterceptor.java:162)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:250)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.requiresNew(CMTTxInterceptor.java:344)
	at org.jboss.as.ejb3.tx.LifecycleCMTTxInterceptor.processInvocation(LifecycleCMTTxInterceptor.java:66)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ee.component.TCCLInterceptor.processInvocation(TCCLInterceptor.java:45)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
	at org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:161)
	... 10 more
Caused by: java.lang.ExceptionInInitializerError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [rt.jar:1.7.0_95]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) [rt.jar:1.7.0_95]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [rt.jar:1.7.0_95]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) [rt.jar:1.7.0_95]
	at org.jboss.msc.value.ConstructedValue.getValue(ConstructedValue.java:61) [jboss-msc-1.0.4.GA.jar:1.0.4.GA]
	at org.jboss.as.naming.ValueManagedReferenceFactory.getReference(ValueManagedReferenceFactory.java:50)
	at org.jboss.as.ee.component.ManagedReferenceInterceptorFactory$ManagedReferenceInterceptor.processInvocation(ManagedReferenceInterceptorFactory.java:90)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:248)
	... 19 more
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getClassLoader")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:474) [rt.jar:1.7.0_95]
	at java.security.AccessController.checkPermission(AccessController.java:685) [rt.jar:1.7.0_95]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) [rt.jar:1.7.0_95]
	at java.lang.ClassLoader.checkClassLoaderPermission(ClassLoader.java:1564) [rt.jar:1.7.0_95]
	at java.lang.Class.getClassLoader(Class.java:623) [rt.jar:1.7.0_95]
	at org.jboss.logmanager.ClassLoaderLogContextSelector.getLogContext(ClassLoaderLogContextSelector.java:84) [jboss-logmanager-1.4.0.Final.jar:1.4.0.Final]
	at org.jboss.logmanager.ThreadLocalLogContextSelector.getLogContext(ThreadLocalLogContextSelector.java:58) [jboss-logmanager-1.4.0.Final.jar:1.4.0.Final]
	at org.jboss.logmanager.LogContext.getLogContext(LogContext.java:290) [jboss-logmanager-1.4.0.Final.jar:1.4.0.Final]
	at org.apache.log4j.JBossLogManagerFacade.getJBossLogger(JBossLogManagerFacade.java:38)
	at org.apache.log4j.JBossLogManagerFacade.getJBossRootLogger(JBossLogManagerFacade.java:98)
	at org.apache.log4j.JBossLogManagerFacade.getLoggerRepository(JBossLogManagerFacade.java:49)
	at org.apache.log4j.LogManager.getLoggerRepository(LogManager.java:49)
	at org.apache.log4j.LogManager.getLogger(LogManager.java:57)
	at org.apache.log4j.Logger.getLogger(Logger.java:39)
	at org.mobicents.slee.test.suite.tckwrapper.SleeTCKPluginWrapper.<clinit>(SleeTCKPluginWrapper.java:46)
	... 32 more

18:33:31,678 ERROR [org.jboss.as.server] (DeploymentScanner-threads - 2) JBAS015870: Deploy of deployment "restcomm-slee-tck-plugin-bean.jar" was rolled back with the following failure message: 
{"JBAS014671: Failed services" => {"jboss.deployment.unit.\"restcomm-slee-tck-plugin-bean.jar\".component.SleeTCKPluginWrapper.START" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"restcomm-slee-tck-plugin-bean.jar\".component.SleeTCKPluginWrapper.START: java.lang.IllegalStateException: JBAS011048: Failed to construct component instance
    Caused by: java.lang.IllegalStateException: JBAS011048: Failed to construct component instance
    Caused by: javax.ejb.EJBException: JBAS014580: Unexpected Error
    Caused by: java.lang.ExceptionInInitializerError
    Caused by: java.security.AccessControlException: access denied (\"java.lang.RuntimePermission\" \"getClassLoader\")"}}
18:33:31,703 INFO  [org.telestax.slee.container.build.as7.deployment.SleeDeploymentInstallProcessor] (MSC service thread 1-2) Undeploy: deployment "restcomm-slee-tck-plugin-bean.jar"

But I added codeBase for this TCK Plugin as:

grant codeBase "file:${jboss.home.dir}/standalone/deployments/restcomm-slee-tck-plugin-bean.jar" {
	permission java.security.AllPermission;
};

**Comment by deruelle** [comment]
@SergeyLee you may need to add more permissions for jars in directory modules/system/layers/base/org/jboss/as such as EJB3 and maybe logging too. Is there a way to add a full subdirectory tree ie modules/system/layers/base/org/jboss by example to include all the sub directories and jars ?

**Comment by SergeyLee** [comment]
@deruelle did you mean this?

Only org.jboss.as:

grant codeBase "file:${jboss.home.dir}/modules/system/layers/base/org/jboss/as/-" {
   permission java.security.AllPermission;
};

All modules:
grant codeBase "file:${jboss.home.dir}/modules/-" {
   permission java.security.AllPermission;
};

I tried with 
grant codeBase "file:${jboss.home.dir}/-" {
   permission java.security.AllPermission;
};
and got this error too.

**Comment by deruelle** [comment]
mmm weird, I would recommend opening a thread with the jboss folks on their forums.

**Comment by satanatoly** [comment]
The TCK is passing now for wildfly
